server:
  port: 9092
  servlet:
    context-path: /tripprofile


  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.jdbc.core: INFO
