server:
  port: 9092
  servlet:
    context-path: /tripprofile

spring:
  datasource:
    url: jdbc:postgresql://pg-tripprofile:5432/app
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: info
    org.springframework.web: info
